### ISSUE TITLE
Chinese Sogou IME is not working

### ISSUE THREAD

**Issue by miloira** [Eugeny/tabby#4999]
Version: 1.0.164
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm
![image](https://user-images.githubusercontent.com/51477120/143733298-789d8d33-f448-4015-b37c-e88dc7d84892.png)

**Comment by elvismile** [comment]
同样的问题，使用微软拼音可以输入，搜狗输入法不行

**Comment by Eugeny** [comment]
Sogou input event handling got broken in Electron 13. I've just pushed a new nightly build with an experimental fix for this - please try it and let me know whether it works for you!

**Comment by Eugeny** [comment]
Sogou input event handling got broken in Electron 13. I've just pushed a new nightly build with an experimental fix for this - please try it and let me know whether it works for you! @miloira @elvismile @geekheitian @timnick-snow @sohero @lanzhiquan @Alex-duzhichao @sswangifly

**Comment by timnick-snow** [comment]
> Sogou input event handling got broken in Electron 13. I've just pushed a new nightly build with an experimental fix for this - please try it and let me know whether it works for you! @miloira @elvismile @geekheitian @timnick-snow @sohero @lanzhiquan @Alex-duzhichao @sswangifly

not work~
![image](https://user-images.githubusercontent.com/33312542/158040287-9bb511c1-9cc6-4181-b141-be6c0140f3df.png)

**Comment by Alex-duzhichao** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/9667107/158167872-8fe9f66e-4a1b-4475-838e-7c3a33ef81ed.png">
@Eugeny not work

**Comment by Alex-duzhichao** [comment]
> Thanks for checking - I've pushed another fix, could you give it a try?

<img width="519" alt="image" src="https://user-images.githubusercontent.com/9667107/158290446-5f2d437e-aaf7-4bc5-aaee-4a198051808c.png">
@Eugeny Works for me. Thank you very much!

**Comment by timnick-snow** [comment]
@Eugeny    Now I can use sogou IME to input Chinese. But there is still a small BUG. When you enter a word in Chinese, press Shift to switch to English. The entered characters still do not display properly.

![image](https://user-images.githubusercontent.com/33312542/159113132-f206bf90-23f3-4713-9ab5-d20248603895.png)
then enter shift. nothing display.
It is normal to use Microsoft Pinyin or sogou in other editors

**Comment by Eugeny** [comment]
Thanks! Could you please explain exactly what Shift should be doing? (I'm not familiar with Sogou).

**Comment by timnick-snow** [comment]
@Eugeny    For example, if I type "haha", "sogou" will display the Chinese character for "haha". But at this point I just want to display the original input character "haha", and I will press Shift, and the editor should just display the original input character "haha".

**Comment by Eugeny** [comment]
I've investigated it and it's the same issue as the previous one - it's due to Sogou not sending `compositionupdate` and `keydown` events to apps built with Electron 13. Unfortunately there's no clean way for me to emulate `compositionupdate`. The workaround is to press Shift _before_ typing.

You can follow https://github.com/xtermjs/xterm.js/issues/3699 in case there will be updates to this topic.
