### ISSUE TITLE
Alpha 204 does not open on Linux Mint 21.2

### ISSUE THREAD

**Issue by BinaryShrub** [Eugeny/tabby#9258]
**Describe the problem**:
When trying to open Tabby Alpha 204 on a fresh install of Linux Mint 21.2, it fails to open.

**To Reproduce**:
1. Clean install of Linux Mint 21.2
2. Install Alpha 204: `wget https://github.com/Eugeny/tabby/releases/download/v1.0.204/tabby-1.0.204-linux-x64.deb && sudo dpkg -i tabby-1.0.204-linux-x64.deb; rm tabby-1.0.204-linux-x64.deb`
3. Open Menu, find Tabby, launch it
4. (nothing happens)
5. Downgrade to Alpha 201: `wget https://github.com/Eugeny/tabby/releases/download/v1.0.201/tabby-1.0.201-linux-x64.deb && sudo dpkg --force-all -i tabby-1.0.201-linux-x64.deb; rm tabby-1.0.201-linux-x64.deb`
3. Open Menu, find Tabby, launch it
4. (it works)

Reproducable for me 100% of the time.

**Comment by richard-kramer** [comment]
I've got the same problem on Ubuntu 23.04. Downgraded to Alpha 201 and it's working again.

**Comment by Clem-Fern** [comment]
Fixed by #9238

You can use nightly build in wait of the next release. https://nightly.link/Eugeny/tabby/workflows/build/master


Duplicated of #9235

**Comment by DoctorU** [comment]
So:
Installing alpha 201 works. Running `tabby` from the standard terminal opens Tabby. 

Update to alpha 204. Run `tabby` from zsh:

```
2023-11-21T13:52:45+00:00 ~> tabby                                                                                                                      stephen
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}

```

And node doesn't exit. 

It's certainly something to do with `node-pty`.

**Comment by Clem-Fern** [comment]
I recommend you to update to the latest release.
It has been fixed in 1.0.205

**Comment by DoctorU** [comment]
@Clem-Fern thanks. I thought 205 had been "fixed" only by reverting some libraries. I hoped my comment will help to identify the update at fault, and a way forward.

**Comment by Clem-Fern** [comment]
@DoctorU Nop, this has really been fixed, but thank's anyway ^^

**Comment by fquinner** [comment]
FYI I installed https://github.com/Eugeny/tabby/releases/download/v1.0.205/tabby-1.0.205-linux-x64.rpm and I'm still seeing this issue on a CentOS 7 install.
